- name: My_ansible_Project v0.1
  gather_facts: false
  hosts: [local]
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
#    IMAGE_NAME: docker_image.name
  tasks:
#    - debug: var=ansible_host
    - name: Git pull repo
      git:
        repo: git@github.com:Crycrime/ansible_playbook.git
        clone: yes
        recursive: yes
        dest: ./repo

    - name: Docker container build
      docker_image:
        name: node_js
        docker_host: unix://var/run/docker.sock
        build:
          path: ./repo
        state: build

#    - name: Docker run image
#      docker:
#        name: node_js


#    - name: stop docker_container
#      shell: docker rm -f node_js > /dev/null 2>&1 && echo 'removed container' || echo 'nothing to remove'

#    - name: Run docker_container
#      command: docker run -it -d --name node_js -p8081:8080 node:12
