- name: My_ansible_Project v0.1
  gather_facts: false
  hosts: [local]
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
#    IMAGE_NAME: docker_image.name
  tasks:
#    - debug: var=ansible_host
    - name: Git pull repo
      git:
        repo: git@github.com:Crycrime/ansible_playbook.git
        dest: ./

    - name: Docker container build
      docker_image:
        name: node_js
        build:
          path: ./
        state: present
        push: no

    - name: stop docker_container
      command: docker stop node:12 || true && docker rm node:12 || true

    - name: run docker_container
      command: docker run -d -p8081:8080 node:12
