- name: My_ansible_Project v0.1
  gather_facts: false
  hosts: [local]
  vars:
    ansible_python_interpreter: /usr/bin/python3
    IMAGE_NAME: docker_image.name
  tasks:
    - debug: var=ansible_host
  connection: local
  tasks:
    - name: Git pull repo
      git:
        repo: git@github.com:Crycrime/ansible_playbook.git
        dest: ./

    - name: Docker container build
      docker_image:
        name: node:12
        build.dockerfile: ./
        state: present
        push: no

    - name: run docker_container
      command: docker run -it -d node:12
