- name: My_ansible_Project v0.1
  gather_facts: false
  hosts: [local]
  vars:
    ansible_python_interpreter: /usr/bin/python3
    IMAGE_NAME: docker_container.name
  tasks:
    - debug: var=ansible_host
  connection: local
  tasks:
    - name: Git pull repo
      git:
        repo: git@github.com:Crycrime/ansible_playbook.git
        dest: ./

    - name: Docker container build
      community.general.docker_container:
        name: node-js
          build:
            path: ./
          source: Build        
        state: present
        published_ports:
          - 8085:8080

    - name: run docker_container
      command: docker run -it --name="$IMAGE_NAME" "$IMAGE_NAME" /bin/bash
